### ISSUE TITLE
Heatmap broken with Chromium Version 40.0.2214.111 (64-bit)

### ISSUE THREAD

**Issue by d-ani-s** [Xosofox/IPAS#42]
Hi,
I'm trying to implement heatmap.js plugin on my projects,  but it seems does not work on Chromium Version 40.0.2214.111 (64-bit). I get the following error: 

Uncaught ReferenceError: h337 is not defined

Here is the code I use

/* Heatmap Options */
var deviceWidth = 414;
var deviceHeight = 736;

var touches =   {
    maxTouchesCount: 4,
    touchEvents:
        [
            { x: 117, y: 140, value: 1 },
            { x: 117, y: 140, value: 1 },
            { x: 117, y: 140, value: 4 },
            { x: 117, y: 140, value: 2 },
            { x: 117, y: 140, value: 4 },
            { x: 117, y: 140, value: 2 },
            { x: 117, y: 140, value: 3 },
            { x: 117, y: 140, value: 3 },
            { x: 150, y: 310, value: 1 },
            { x: 150, y: 310, value: 1 }
        ]
}
function createHeatmap()
{
    var mainBlock    = document.getElementById('hm-papa');
    var heatmapBlock = document.createElement('div');
    heatmapBlock.setAttribute('class', 'heatmap');
    heatmapBlock.setAttribute('id', 'heatmap_area');
    heatmapBlock.setAttribute("background-color", 'red');
    mainBlock.appendChild(heatmapBlock);
    $('.heatmap').css('width', deviceWidth);
    $('.heatmap').css('height', deviceHeight);
    var createdHeatmap = h337.create({"element":document.getElementById("heatmap_area"), radius : 10});
    createdHeatmap.store.setDataSet({max : touches.maxTouchesCount,   data : touches.touchEvents});
}

What's wrong with code, or there is an issue with plugin?

**Comment by Xosofox** [comment]
The heatmap plugin is a library by http://www.patrick-wied.at/static/heatmapjs/ I am just using. 

As the heatmap still works on IPAS (I use the same chrome version), I'd assume there is an issue with the library not being correctly loaded in your test

**Comment by d-ani-s** [comment]
Ok. Than,  should I include the plugin in the bottom of the body. Or It's ok that I've included it in the head section?

**Comment by Xosofox** [comment]
As you can see in the IPAS code, I've added it in the header and it works fine
