### ISSUE TITLE
Show XMP Count

### ISSUE THREAD

**Issue by cmnisal** [Xosofox/IPAS#47]
Required XMP count to neutralize portal

**Comment by Xosofox** [comment]
How exactly should that work, assuming that the position of the shots matters?
What should the number indicate?

**Comment by cmnisal** [comment]
Locked Position can be okay.
Sample stats like this ''How many X8 needed to break P8 with 4AXA''

**Comment by Xosofox** [comment]
Problem is: No-one knows the answer to that. How many X8 do you need to
break an AXA? 1? 100? Whatever the odds are...

2016-06-27 13:21 GMT+02:00 Nisal Chandrasekara <notifications@github.com>:
